[[redirects]]
    from = "/blog/:year/:month/:day/:slug/*"
    to = "/:year/:month/:day/:slug/"
    status = 301
    force = true

# Terms and policies moved to wiki.free.law
[[redirects]]
    from = "/recap/tos/"
    to = "https://wiki.free.law/c/terms/recap-extension/recap-extension-terms-of-use"
    status = 301
    force = true

[[redirects]]
    from = "/recap/privacy-policy/"
    to = "https://wiki.free.law/c/terms/recap-extension/recap-extension-privacy-policy"
    status = 301
    force = true

[[redirects]]
    from = "/recap/dmca/"
    to = "https://wiki.free.law/c/terms/recap-extension/recap-extension-dmca-policy"
    status = 301
    force = true

[[redirects]]
    from = "/vulnerability-disclosure-policy/"
    to = "https://wiki.free.law/c/terms/free-law-project-vulnerability-disclosure-policy-and-bounty-program"
    status = 301
    force = true

[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = 'max-age=63072000; includeSubdomains; preload'

        X-Frame-Options = "DENY"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = 'same-origin'

        # This one only applies to older browsers, and getting good information about what it does it hard.
        # It is superceded by CSP headers, but still useful in old browsers.
        X-XSS-Protection = "1; mode=block"

        # Block Chrome's "Privacy Sandbox"
        permissions-policy = "browsing-topics=()"