[[redirects]]
    from = "/blog/2026/05/12/courtlistener-is-now-available-inside-claude/"
    to = "/2026/05/12/courtlistener-is-now-available-inside-claude/"
    status = 301
    force = true

[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = 'max-age=63072000; includeSubdomains; preload'

        X-Frame-Options = "DENY"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = 'same-origin'

        # This one only applies to older browsers, and getting good information about what it does it hard.
        # It is superceded by CSP headers, but still useful in old browsers.
        X-XSS-Protection = "1; mode=block"

        # Block Chrome's "Privacy Sandbox"
        permissions-policy = "browsing-topics=()"